### ISSUE TITLE
Multi instances of CMS element not possible

### ISSUE THREAD

**Issue by wannevancamp** [shopware/admin-extension-sdk-example-app#1]
We want to add multiple CMS elements to one Shopping Experience. The first element works without any issue, but after adding the second the first element will be replaced by the second element. This results in 2 CMS elements with the same content.

It's not clear if it's a bug in the example code or a bug in Shopware core. 

Docs: https://developer.shopware.com/docs/guides/plugins/plugins/content/cms/add-cms-element-via-admin-sdk
Prinscreen: 
![image](https://github.com/shopware/admin-extension-sdk-example-app/assets/3399877/675a9008-0f96-4a6c-87fe-820e25abe7dc)

**Comment by seggewiss** [comment]
@marcelbrode can you say something about this?

**Comment by marcelbrode** [comment]
I personally can't reproduce this :thinking: So I don't really now where the problem is. Sorry

**Comment by seggewiss** [comment]
@wannevancamp can you give more details on how to reproduce this?

**Comment by wannevancamp** [comment]
Hi @seggewiss , @marcelbrode,

Thanks for having a look.

There are multiple apps in the store which show a message like this:
> Note: Due to Shopware limitations, only 1 element can be inserted per experience world. (Effective: 11.04.2023)

I've set up a new project on the latest Shopware version and [attached a screen recording](https://drive.google.com/file/d/1LE1Hkbkd20062JCBplUwbrSZkwNDyUWW/view?usp=drive_link).

1. `shopware-cli project create project-x 6.5.3.2`
2. `symfony console system:install --basic-setup --drop-database --create-database -f`
3. Follow the [Readme](https://github.com/shopware/admin-extension-sdk-example-app/blob/main/README.md)
4. Create a CMS page
5. Add some default CMS blocks ex. text, image,...
6. Replace them with the Dailymotion video CMS element and configure the Dailymotion video code.

**Result**
The CMS element shows the same instance
See [screen recording](https://drive.google.com/file/d/1LE1Hkbkd20062JCBplUwbrSZkwNDyUWW/view?usp=drive_link).

**Expected**
Each instance of a CMS element should show its own content. You would expect one video of 'funny cats' and one with 'funny dogs'. This issue is not related to the videos but to CMS elements in general.

**Comment by wannevancamp** [comment]
Hi @seggewiss , @marcelbrode, do you have feedback on this one?
Thanks a lot!

**Comment by wannevancamp** [comment]
It looks like @jleifeld provided a fix for this issue: https://github.com/shopware/shopware/commit/027a10d53a6f92591e90921f9a44fbf00e57bd54

**Comment by hungmac-sw** [comment]
Hi @jleifeld, thank you for taking care of this issue. I noticed that there is an issue with authenticating. Shopware doesn't send the parameters to the authentication. Or am I missing something?
<img width="1245" alt="Screenshot 2023-10-31 at 19 49 23" src="https://github.com/shopware/admin-extension-sdk-example-app/assets/60767402/973706df-ed90-4507-9e31-c2659ddf750a">
